# Generated by Django 3.2.6 on 2021-08-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='BudgetItem',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
