# Generated by Django 3.2.6 on 2021-08-04 20:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0002_auto_20210804_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.FloatField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.weddingplanner')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.SmallIntegerField()),
                ('comment', models.TextField(max_length=5000)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.weddingplanner')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('rsvp', models.CharField(choices=[('P', 'Pending'), ('A', 'Attending'), ('D', 'Declined')], default='P', max_length=1)),
                ('wedplanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.weddingplanner')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('cost', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('balance_cleared', models.BooleanField(default=False)),
                ('wedplanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.weddingplanner')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.vendor')),
            ],
        ),
    ]
