# Generated by Django 3.2.6 on 2021-08-06 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0003_bookmark_budgetitem_guest_review_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a category (EG: Wedding venue)', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['rsvp']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='balance_cleared',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(help_text='When would you like to have this done?', null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Attending'), ('D', 'Declined')], default='P', help_text='rsvp status', max_length=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(help_text='Select a category for your business.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamwed.vendorcategory'),
        ),
    ]
