# Generated by Django 3.2.6 on 2021-08-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0004_auto_20210807_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='category',
            new_name='vendor_category',
        ),
    ]
