# Generated by Django 3.2.6 on 2021-08-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0005_rename_category_vendor_vendor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.ForeignKey(help_text='Select a category for your business.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamwed.vendorcategory'),
        ),
    ]
