# Generated by Django 3.2.6 on 2021-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0007_auto_20210808_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, help_text='When would you like to have this done?', null=True),
        ),
        migrations.AlterField(
            model_name='weddingplanner',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
