# Generated by Django 3.2.6 on 2021-08-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0012_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamwed.vendorcategory'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='cost',
            field=models.FloatField(blank=True, help_text='Would you like to create a budget for this task?', null=True),
        ),
    ]
