# Generated by Django 3.2.6 on 2021-08-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0014_auto_20210810_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamwed.weddingplanner'),
        ),
    ]
