# Generated by Django 3.2.6 on 2021-08-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0015_alter_expensecategory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='wedplanner',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='user',
            new_name='wedplanner',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='wedplanner',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='wedplanner',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='cost',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamwed.expensecategory'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='cost',
            field=models.FloatField(blank=True, help_text='What is the estimated cost of this budget item?', null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='paid',
            field=models.FloatField(blank=True, help_text='How much have you paid for this budget item so far?', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('wedplanner', 'vendor')},
        ),
    ]
