# Generated by Django 3.2.6 on 2021-09-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0017_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_img_uploads')),
                ('caption', models.CharField(max_length=500)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamwed.vendor')),
            ],
        ),
    ]
