# Generated by Django 3.2.6 on 2021-09-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0018_imageupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUpload',
            new_name='VendorImageUpload',
        ),
    ]
