# Generated by Django 3.2.6 on 2021-09-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0019_rename_imageupload_vendorimageupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorimageupload',
            name='image',
            field=models.ImageField(upload_to='vendor_img_uploads'),
        ),
    ]
