# Generated by Django 3.2.6 on 2021-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0020_alter_vendorimageupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingplanner',
            name='partner_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weddingplanner',
            name='partner_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
