# Generated by Django 3.2.6 on 2021-09-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0021_auto_20210912_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingplanner',
            old_name='partner_fname',
            new_name='partner_first_name',
        ),
        migrations.RenameField(
            model_name='weddingplanner',
            old_name='partner_lname',
            new_name='partner_last_name',
        ),
    ]
