# Generated by Django 3.2.6 on 2021-09-13 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0023_auto_20210913_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
