# Generated by Django 3.2.6 on 2021-09-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0024_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='note',
            field=models.EmailField(default='no note', max_length=1024),
            preserve_default=False,
        ),
    ]
