# Generated by Django 3.2.6 on 2021-09-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0025_guest_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='note',
            field=models.CharField(max_length=1024),
        ),
    ]
