# Generated by Django 3.2.6 on 2021-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0026_alter_guest_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Attending', 'Attending'), ('Declined', 'Declined')], default='Pending', help_text='rsvp status', max_length=20),
        ),
    ]
