# Generated by Django 3.2.6 on 2021-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0027_alter_guest_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingplanner',
            name='wedding_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
