# Generated by Django 3.2.6 on 2021-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0028_weddingplanner_wedding_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='cost',
            field=models.FloatField(default=0.0, help_text='What is the estimated cost of this budget item?'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='paid',
            field=models.FloatField(default=0.0, help_text='How much have you paid for this budget item so far?'),
        ),
        migrations.AlterField(
            model_name='weddingplanner',
            name='wedding_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
