# Generated by Django 3.2.6 on 2021-09-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamwed', '0030_auto_20210927_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='cost',
            field=models.FloatField(blank=True, default=0.0, help_text='What is the estimated cost of this budget item?', null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='paid',
            field=models.FloatField(blank=True, default=0.0, help_text='How much have you paid for this budget item so far?', null=True),
        ),
    ]
